const projets: {
    text: string;
    id: string;
    list: {
      id: string;
      titre: string;
      organizer: string;
      place: string;
      date: string;
      img: string;
      description: string;
    }[];
  }[] = [
    {
      text: "Manifestations Zonales",
      id: 'manifestations',
      list: [
        {id:"rzpa", titre:"2ème Réunion Zonale des Présidents de la Zone A", organizer:"JCI Manouba & JCI Tunisie-Zone A", place:"Salle des fêtes Nedra à Manouba", date:"16 Juillet, 2023", img:"./assets/img/programmes/manifestations/rzpa.jpg", description:"La participation de la jeune chambre économique du Bardo au 2ème RZP&2ème\nCRF de la zone A qui se sont déroulés le 16 juillet 2023 à la salle des fêtes Nedra à Manouba.\nDurant cette journée, JCI BARDO était remarquable par son engagement\nindéfectible envers l\'efficacité et la réalisation de résultats concrets qui sont:\n• L\'OLM LA plus efficace de la zone A durant la 2ème trimestre (Avril - Mai- Juin)\n• Top 5 l\' OLM la plus active des formations durant le 1er semestre.\n• Top 3 l\'OLM de nombres de formations (Avril-Mai-Juin)\n• Cyrine Ouertateni est la 2ème formatrice plus remarquable de la zone A .\n• Cyrine Ouertateni la formatrice la plus active en Co-formation durant les mois Avril-Mai-Juin\n• Cyrine Ouertateni est la 2ème formatrice la plus remarquable durant la période Avril-Mai-Juin.\n• Wissem Sammoud le 2ème formateur le plus actif en Co-formation."},
        {id:"assisedeprintemps", titre:"Les Assises de Printemps", organizer:"JCI Bardo & JCI Tunisie-Zone A", place:"Yasmine Hammamet", date:"18-19 Mars, 2023", img:"./assets/img/programmes/manifestations/assisesdeprintemps.jpg", description:""}
      ]
    },
    {
      text: "Projets Locaux",
      id: 'projets_locaux',
      list: [
        {id:"ecovertemarchevert", titre:"Eco-verte 2.0 : Marché-vert Foire Bio", organizer:"JCI Bardo & Municipalité du Bardo", place:"Le Bardo", date:"24 Septembre, 2023", img:"./assets/img/programmes/projetslocaux/marche-vert.jpg", description:"La Jeune Chambre Internationale du Bardo, en\npartenariat avec la Municipalité de Bardo a organisé\nun événement intitulé « Marché Vert » le 24 Septembre à 9h devant Monoprix de l\'avenue Habib\nBourguiba Bardo.\n\nDans ce cadre des exposants proposeront des produits\nécologiques naturels et d\'autres à partir des matières\nou déchets recyclés afin d\'encourager la\ncommunauté et les habitants à l\'importance de la\npréservation de notre planète pour les générations futures."},
        {id:"recrutementksarsaid2", titre:"Recrutement citoyens ksar-Said", organizer:"JCI Bardo", place:"Le Bardo", date:"03 Septembre, 2023", img:"./assets/img/programmes/projetslocaux/recrute2.jpg", description:"𝑽𝒊𝒔𝒐𝒏𝒔 𝒂 ê𝒕𝒓𝒆 𝒍𝒆 𝒑𝒓𝒊𝒏𝒄𝒊𝒑𝒂𝒍 𝒓𝒆𝒔𝒆𝒂𝒖 𝒎𝒐𝒏𝒅𝒊𝒂𝒍 𝒅𝒆𝒔 𝒋𝒆𝒖𝒏𝒆𝒔 𝒍𝒆𝒂𝒅𝒆𝒓𝒔\".\nLa 𝕵𝖊𝖚𝖓𝖊 𝕮𝖍𝖆𝖒𝖇𝖗𝖊 𝕴𝖓𝖙𝖊𝖗𝖓𝖆𝖙𝖎𝖔𝖓𝖆𝖑𝖊 𝖉𝖚 𝕭𝖆𝖗𝖉𝖔 a\norganisé le 03 Septembre 2023 une journée de\nrecrutement à la 𝐦𝐚𝐢𝐬𝐨𝐧 𝐝𝐞𝐬 𝐣𝐞𝐮𝐧𝐞𝐬 𝐁𝐨𝐫𝐭𝐚𝐥 𝐇𝐚𝐲𝐝𝐞𝐫.\n\nCela s\’inscrit dans le cadre de la volonté de\nnotre jeune chambre dans la valorisation des\ncapacités des jeunes cityons actifs de 𝐊𝐬𝐚𝐫 𝐒𝐚𝐢𝐝 et de faire progresser leurs compétences\nafin d\’apporter une contribution positive et\nefficace à leurs communauté."},
        {id:"journeeenseignants", titre:"Journée des enseignants", organizer:"JCI Bardo & ANETI", place:"Le Bardo", date:"21 Août, 2023", img:"./assets/img/programmes/projetslocaux/journée-ens.jpg", description:""},
        {id:"recrutementksarsaid1", titre:"Recrutement citoyens ksar-Said", organizer:"JCI Bardo", place:"Maison des jeunes Bortal", date:"17 Juin, 2023", img:"./assets/img/programmes/projetslocaux/recrute.jpg", description:"𝑽𝒊𝒔𝒐𝒏𝒔 𝒂 ê𝒕𝒓𝒆 𝒍𝒆 𝒑𝒓𝒊𝒏𝒄𝒊𝒑𝒂𝒍 𝒓𝒆𝒔𝒆𝒂𝒖 𝒎𝒐𝒏𝒅𝒊𝒂𝒍 𝒅𝒆𝒔 𝒋𝒆𝒖𝒏𝒆𝒔 𝒍𝒆𝒂𝒅𝒆𝒓𝒔\".\nLa 𝕵𝖊𝖚𝖓𝖊 𝕮𝖍𝖆𝖒𝖇𝖗𝖊 𝕴𝖓𝖙𝖊𝖗𝖓𝖆𝖙𝖎𝖔𝖓𝖆𝖑𝖊 𝖉𝖚 𝕭𝖆𝖗𝖉𝖔 a\norganisé le 17 juin 2023 une journée de\nrecrutement à la 𝐦𝐚𝐢𝐬𝐨𝐧 𝐝𝐞𝐬 𝐣𝐞𝐮𝐧𝐞𝐬 𝐁𝐨𝐫𝐭𝐚𝐥 𝐇𝐚𝐲𝐝𝐞𝐫.\n\nCela s\’inscrit dans le cadre de la volonté de\nnotre jeune chambre dans la valorisation des\ncapacités des jeunes cityons actifs de 𝐊𝐬𝐚𝐫 𝐒𝐚𝐢𝐝 et de faire progresser leurs compétences\nafin d\’apporter une contribution positive et\nefficace à leurs communauté."},
        {id:"emccloture", titre:"Entrepreneurship Masterclass 3.0 : Cérémonie de clôture", organizer:"JCI Bardo & INJAZ Tunisie", place:"Maison des jeunes Bortal", date:"04 Juin, 2023", img:"./assets/img/programmes/projetslocaux/cloture emc.jpg", description:"La 𝑱eune 𝑪hambre 𝑬conomique du 𝑩𝒂𝒓𝒅𝒐 a récemment organisé une 𝐜é𝐫é𝐦𝐨𝐧𝐢𝐞 𝐝𝐞 𝐜𝐥ô𝐭𝐮𝐫𝐞 toute particulière de notre projet 𝔼𝕟𝕥𝕣𝕖𝕡𝕣𝕖𝕟𝕖𝕦𝕣𝕤𝕙𝕚𝕡 𝕄𝕒𝕤𝕥𝕖𝕣𝕔𝕝𝕒𝕤𝕤 💼, auquel croit fermement notre cher partenaire 𝗜𝗻𝗷𝗮𝘇 𝗧𝘂𝗻𝗶𝘀, qui ne cessera de soutenir ce Noble projet visant le développement économique.\nsoyez bienvenue à la 𝐥𝐚 𝐦𝐚𝐢𝐬𝐨𝐧 𝐝𝐞𝐬 𝐣𝐞𝐮𝐧𝐞𝐬 𝐁𝐨𝐫𝐭𝐚𝐥 le dimanche 4 𝗷𝘂𝗶𝗻 2023 pour soutenir les entrepreneurs juniors et encourager ce genre d\'impact positif sur l\'ensemble de la communauté."},
        {id:"smallbusinessexpo", titre:"معرض للمشاريع الصغرى", organizer:"JCI Bardo & ANETI", place:"Le Bardo", date:"02 Juin, 2023", img:"./assets/img/programmes/projetslocaux/expo.jpg", description:"La 𝐉eune 𝐂hambre 𝐄conomique du Bardo s\'implique activement dans\nl\'organisation de la Journée d\'𝔼𝕩𝕡𝕠𝕤𝕚𝕥𝕚𝕠𝕟 𝕕𝕖𝕤 ℙ𝕖𝕥𝕚𝕥𝕤 ℙ𝕣𝕠𝕛𝕖𝕥𝕤 le 2 juin 2023 avec Bureau de l\'Emploi et du Travail Indépendant de Bardo 𝗔𝗡𝗘𝗧𝗜.\nCette initiative vise à promouvoir et soutenir les jeunes entrepreneurs locaux en\nmettant en valeur leurs réalisations et en bénéficiant des expériences de jeunes entrepreneurs.\nEn tant que 𝐉𝐂𝐈 𝐁𝐚𝐫𝐝𝐨, nous avons été invités à soutenir l\'organisation de cette journée d\'exposition.\nNotre engagement consistera à animer des stands pour les participants et les\nvisiteurs afin d\'inciter les jeunes à acquérir des compétences pour faciliter l\'émergence de projets prometteurs."},
        {id:"journeeinformation", titre:"Participation à la journée d'information", organizer:"ANETI", place:"Faculté des sciences de tunis", date:"26 Mai, 2023", img:"./assets/img/programmes/projetslocaux/journée-information.jpg", description:""},
        {id:"santesexuelle", titre:"GrowUP : Journée de sensibilisation sur la santé sexuelle et reproductive", organizer:"JCI Bardo", place:"Le Bardo", date:"19 Mai, 2023", img:"./assets/img/programmes/projetslocaux/santesexuelle.jpg", description:"Le 19 Mai 2023, 𝐋𝐚 𝐉𝐞𝐮𝐧𝐞 𝐂𝐡𝐚𝐦𝐛𝐫𝐞 𝐄𝐜𝐨𝐧𝐨𝐦𝐢𝐪𝐮𝐞 𝐝𝐮 𝐁𝐚𝐫𝐝𝐨 a\norganisé en collaboration avec 𝐀𝐓𝐋 𝐌𝐒𝐓 𝐒𝐈𝐃𝐀 TUNIS\nTunis une 2ème Journée dans le projet \"𝙶𝚁𝙾𝚆 𝚄𝙿\"\ndans le cadre de 𝐬𝐞𝐧𝐬𝐢𝐛𝐢𝐥𝐢𝐬𝐚𝐭𝐢𝐨𝐧 𝐬𝐮𝐫 𝐥𝐚 𝐬𝐚𝐧te 𝐬𝐞𝐱𝐮𝐞𝐥𝐥𝐞 𝐞𝐭\n𝐫𝐞𝐩𝐫𝐨𝐝𝐮𝐜𝐭𝐢𝐯𝐞 qui s\'est déroulée au Lycée Bayrem Tounsi Bardo.\n\nL\'objectif de cette journée est de sensibiliser les\njeunes sur :\n𝗹𝗲𝘀 𝗠𝗮𝗹𝗮𝗱𝗶𝗲𝘀 𝘀𝗲𝘅𝘂𝗲𝗹𝗹𝗲𝗺𝗲𝗻𝘁 𝘁𝗿𝗮𝗻𝘀𝗺𝗶𝘀𝘀𝗶𝗯𝗹𝗲𝘀 𝗲𝘁 𝗹𝗲𝘀 𝗠𝗼𝘆𝗲𝗻𝘀 𝗱𝗲 𝗽𝗿é𝘃𝗲𝗻𝘁𝗶𝗼𝗻."}
      ]
    },
    { 
      text: "Projets Internationaux",
      id: 'projets_internationaux',
      list: [
        {id:"letstalkglobally1", titre:"Let's Talk Globally", organizer:"JCI Aleppo", place:"sur Google Meet", date:"21-28 Août | 04-11 Septembre, 2023", img:"./assets/img/programmes/projetsinternationaux/talkglobally.jpg", description:"هل أنتم جاهزون لرحلة حول العالم وانتم خلف شاشاتكم؟!\n من منّا لم يحلم يوماً بالسفر حول العالم للتعرّف على جميع الأماكن الجميلة فيه؟ من منّا لم يرغب في تجربة التعرّف على ثقافات وعادات وتقاليد الناس؟\n من هنا أتت فكرة Let\’s Talk Globally لنتمكّن من تجربة الثقافات الأخرى دون حتى الحاجة إلى مغادرة بيوتنا!\n حيث ترتكز الفكرة الأساسية في استخدام الانترنت كوسيلة لاختصار المسافات بين الناس عن طريق إقامة عدة جلسات بين كل من:\n الغرفة الفتية الدولية حلب (سورية) -الغرفة الفتية الدولية باردو (تونس) - الغرفة الفتية الدولية السويداء (سورية) - الغرفة الفتية الدولية طرطوس (سورية) - الغرفة الفتية الدولية فيلا ماريا (الأرجنتين) -الغرفة الفتية الدولية مانشستر (بريطانيا) - الغرفة الفتية الدولية مراكش(المغرب).\n تقدم كل غرفة فيها عرضاً تقديمياً في جلسة يتحدث فيها المشاركون فيها الأصدقاء عن الموسيقى في بلدهم، العادات والتقاليد في المناسبات الرسميّة، الأطعمة الشهيرة لديهم، أهم الأماكن الأثرية والسياحية والدينية، بالإضافة الى التعرف على بعضهم البعض وخلق روابط الصلة المتينة والتعرف على صورة البلد وأهله بشكل أفضل كأنك قمت بزيارته وأنت جالس في المنزل مع تصحيح بعض الصور النمطيّة عن البلدان المشاركة.\nAre you ready for a trip worldwide, and you\'re behind your screens?\nWho never dreamed of traveling the world to learn about all the beautiful places in it? Who wanted to experience something other than learning about people\'s cultures, customs, and traditions?\nTherefore the idea of Let\'s Talk Globally is to experience other cultures without leaving our homes!\nThe basic idea is to use the Internet as a means of shortening people\'s distances by holding several sessions between:\nJCI Aleppo   الغرفة الفتية الدولية حلب (Syria) - JCI Bardo(Tunisia) - JCI Lusaka (Zambia) - JCI Marrakech (Morocco) - JCI Manchester JCI(UK) - JCI Sweida   الغرفة الفتية الدولية السويداء (Syria) - JCI Tartus (Syria) - JCI Villa María (Argentina).\nEach Organization presents a presentation at a session where friends talk about music in their country, habits, and traditions at official events, their famous foods, and the most important archaeological, tourist, and religious places, In addition to getting to know each other and creating strong links and better familiarize yourself with the image of the country and its people as if you had visited it while sitting at home while correcting some stereotypes about the participating countries.\nJCI BARDO JCI Lusaka JCI Tartus JCI Villa María JCI Manchester JCI Sweida   الغرفة الفتية الدولية السويداء JCI Marrakech"},
        {id:"conferenceaem", titre:"Conférence Afrique Européenne et Moyen Orient", organizer:"JCI Bardo", place:"sur Zoom", date:"17 Juin, 2023", img:"./assets/img/programmes/projetsinternationaux/conferenceafrique.jpg", description:""},
        {id:"conferencerd", titre:"Conférence Recover from Disaster", organizer:"International", place:"Sur Google Meet", date:"02 Avril, 2023", img:"./assets/img/programmes/projetsinternationaux/recoveringfromdisaster.jpg", description:""},
        {id:"ecoverteecobleu", titre:"Eco-verte 2.0 : Eco Bleue", organizer:"JCI Bardo", place:"sur Google Meet", date:"13-15 Mars, 2023", img:"./assets/img/programmes/projetsinternationaux/ecoverte13-15mars.jpg", description:"🟢 Nous avons lancé la 2ème partie de projet \" Eco-verte 2.0 \" dans le cadre de la conférence internationale en ligne intitulée \"Eco-bleue\" en collaboration avec Relief Action International (RAI).\nLe forum s\'est déroulé sur deux journées le 13 et le 15 Mars 2023\noù nous avons attaqué plusieurs sujets intéressants liés à l\'impact des activités économiques liées aux océans, aux mers et à leurs côtes et la préservation de l\'environnement et la biodiversité."},
        {id:"vda", titre:"La valorisation des déchets aquatiques", organizer:"JCI Bardo & JCI Ciwara", place:"sur Google Meet", date:"17 Août, 2022", img:"./assets/img/programmes/projetsinternationaux/la valorisation des déchets aquatiques.jpg", description:""},
        {id:"ecovertevdper", titre:"Eco-verte : Valorisation des déchets & la production d'énergies renouvelables", organizer:"JCI Bardo", place:"sur Google Meet", date:"06 Mai, 2022", img:"./assets/img/programmes/projetsinternationaux/ecoverte6mai.jpg", description:""},
        {id:"afrotun", titre:"AFROTUN", organizer:"JCI Bardo", place:"sur Google Meet", date:"21-30-31 Mars, 2021", img:"./assets/img/programmes/projetsinternationaux/afrotun.jpg", description:""},
        {id:"rei", titre:"14ème rassemblement des Étudiants Internationaux", organizer:"JCI Bardo", place:"Le Bardo", date:"20 Mars, 2021", img:"./assets/img/programmes/projetsinternationaux/etudiantinternationaux.jpg", description:""}
      ]
    },
    {
      text: "Formations & Forums",
      id: 'formations_forums',
      list: [
        {id:"ecoverteearthforum", titre:"Eco-verte 2.0 : Resilient earth Forum", organizer:"JCI Bardo & Club'y & Youth", place:"Le Bardo", date:"18 Août, 2023", img:"./assets/img/programmes/formationsetforums/earth-forum.jpg", description:"Dans le cadre de son projet \"Éco-verte 2.0\"\n𝗟a Jeune 𝗖hambre 𝗘conomique du 𝗕ardo à organisé, 𝐥𝐞 18 𝐀𝐨𝐮̂𝐭 2023 𝐚̀ 14H au 𝐂𝐥𝐮𝐛'𝐲 𝐥𝐞 𝐁𝐚𝐫𝐝𝐨 , en partenariat avec le mouvement Youth For Climate Tunisia - Community\n\" 𝐑𝐄𝐒𝐈𝐋𝐈𝐄𝐍𝐓 𝐄𝐀𝐑𝐓𝐇 𝐅𝐎𝐑𝐔𝐌 \"\nLa journée s'est ouverte avec la projection du film \" 𝐓𝐡𝐞 11𝐭𝐡 𝐇𝐨𝐮𝐫 𝐫𝐢𝐠𝐡𝐭 \" qui a été suivie par une table ronde où les enjeux environnementaux abordés par le film ont été  discutés.\nNous avons fini notre forum par une séance de cours de calligraphie arabe.\nOn tient à remercier sincèrement club\'y bardo pour l\'aimable accueil ainsi que nos partenaires,\nNous tenons également à remercier nos chers membres pour leurs participation active à cette journée."},
        {id:"microsoft2", titre:"Formation Microsoft by JCI", organizer:"JCI Bardo", place:"sur Zoom", date:"18 Août, 2023", img:"./assets/img/programmes/formationsetforums/micro-jci.jpg", description:"Forum intitulé \" Microsoft by JCI \" qui a eu lieu le\n15,17,18 Août 2023 sur Google Meet, en collaboration\navec INJAZ Tunisia\n\nCette forum en ligne s\'est déroulé sur le pack Microsoft\nOffice est spécialement dédiée pour les membres de la JCI\nqui veulent acquérir de nouvelles compétences\nprofessionnelles. Elle couvre tous les outils indispensables\npour travailler efficacement : Word, Excel, PowerPoint,\nOutlook..\nanimé par nos chers formateurs cyrine ouertarteni et\nWissem Sammoud."},
        {id:"microsoft1", titre:"Formation Microsoft by JCI", organizer:"JCI Bardo", place:"sur Zoom", date:"15, 17, 18 Août, 2023", img:"./assets/img/programmes/formationsetforums/ev-micro.jpg", description:"\"La formation est l\'essence de tout succès\"\nRetour en images sur le forum intitulé \" Microsoft by JCI\" qui a eu lieu le 15,17,18 Août 2023 sur Google Meet, en collaboration avec INJAZ Tunisia  et organisé par Bardo, JCI OLM Oued Ellil, JCI Tebourba, JCI jedaida, JCI France Ville , JCI El Battan , JCI Les Jardins, JCI La Marsa, JCI IBN Khaldoun , JCI Leaders Beb Souika , JCI  OLM  Manouba , JCI nouvelle medina , JCI Mornaguia.\nCe forum a visé le programme de Microsoft  qui est spécialement dédié aux membres de la JCI qui veulent acquérir de nouvelles compétences professionnelles.\nElle couvre tous les outils indispensables pour travailler efficacement : Word, Excel, PowerPoint, Outlook..\nanimé par nos chers formateurs سيرين الورتتاني  et Wissem Sammoud\nOn tient vivement à les remercier pour leur professionnalisme.\nOn a été honoré par l\'intervention de notre vpf de la zone A dans la journée de l\'ouverture,\nNous tenons également à remercier nos chers participants pour leur engagement et leur confiance."},
        {id:"projectmanagement", titre:"Session recommandée: formation project-management", organizer:"JCI Bardo", place:"Le Bardo", date:"13 Août, 2023", img:"./assets/img/programmes/formationsetforums/session-rec.jpg", description:"Retour en images sur la session recommandé intitulée \" 𝐏𝐫𝐨𝐣𝐞𝐜𝐭 𝐌𝐚𝐧𝐚𝐠𝐞𝐦𝐞𝐧𝐭 \" qui a eu lieu 𝑫𝒊𝒎𝒂𝒏𝒄𝒉𝒆 13 𝑨𝒐𝒖𝒕 2023 à la 𝑴𝒖𝒏𝒊𝒄𝒊𝒑𝒂𝒍𝒊𝒕𝒆́ 𝒅𝒖 𝑩𝒂𝒓𝒅𝒐 , animée par nos chers formateurs 𝑵𝒂𝒔𝒔𝒆𝒓𝒆𝒅𝒅𝒊𝒏 𝑴𝒆𝒄𝒉𝒓𝒊 et 𝑪𝒚𝒓𝒊𝒏𝒆 𝑶𝒖𝒆𝒓𝒕𝒂𝒕𝒆𝒏𝒊 qu'on tient par cette occasion à les remercier pour leurs professionnalisme et leurs efforts déployés.\nSans oublier de remercier nos chers membres pour leurs engagements pour faire réussir le déroulement de la formation."},
        {id:"cafetalkpsychologie", titre:"Cafe Talk : Psychologie", organizer:"JCI Bardo", place:"Le Bardo", date:"05 Août, 2023", img:"./assets/img/programmes/formationsetforums/ev-talk.jpg", description:"Retour en images sur le Café Talk sous le thème \" Café Talk... هيا نحكيو Psychologie \" qui a eu lieu 𝐒𝐚𝐦𝐞𝐝𝐢 5 𝐀𝐨𝐮̂𝐭  2023 dans 𝐥𝐞 𝐜𝐚𝐟𝐞́ 𝐁𝐨𝐧𝐳𝐚𝐢 𝐁𝐚𝐫𝐝𝐨. \nLe café talk a été animée  par l'intervention de nos chers psychologues 𝐌𝐚𝐫𝐚𝐦 𝐃𝐨𝐠𝐡𝐫𝐢  et 𝐑𝐚𝐡𝐦𝐚 𝐂𝐡𝐚𝐢𝐛𝐢 , qui ont partagé leurs connaissances et leurs expériences pour permettre aux membres de connaître les maladies mentales, résoudre les difficultés d’ordre psychique . \npar cette occasion, On tient à les remercier pour leurs professionalismes et leurs soutiens psychologiques . \nSans oublier de remercier nos chers membres pour leurs engagements."},
        {id:"canadianresume", titre:"Formation the A B C’s of a Canadian Resume", organizer:"JCI Bardo", place:"sur Google Meet", date:"02 Août, 2023", img:"./assets/img/programmes/formationsetforums/canadian-resume.jpg",description:"Retour en images sur la session officielle intitulée \" 𝐓𝐡𝐞 𝐀𝐁𝐂\'𝐬 𝐨𝐟 𝐚 𝐂𝐚𝐧𝐚𝐝𝐢𝐚𝐧 𝐑𝐞𝐬𝐮𝐦𝐞  \" qui a eu lieu 𝐌𝐞𝐫𝐜𝐫𝐞𝐝𝐢 2 𝐀𝐨𝐮̂𝐭  2023 sur 𝐆𝐨𝐨𝐠𝐥𝐞 𝐌𝐞𝐞𝐭 . \nCette Formation a été animée animée par notre chére Formatrice 𝐘𝐨𝐬𝐫𝐚 𝐁𝐞𝐧 𝐀𝐛𝐝𝐚𝐥𝐥𝐚𝐡 ,\nqui a partagé ses connaissances et son expérience pour permettre aux membres de connaître les types de Resume le plus répandues, les parties d\'un résumé, les caractéristiques d\'un Cv canadien et les erreurs à éviter. \npar cette occasion, on tient à  remercier notre chère formatrice pour leur professionnalisme et leur efforts tous au long de la formation. \nSans oublier de remercier nos chers membres pour leurs engagements pour faire réussir le déroulement de la formation."},
        {id:"jcipresenter", titre:"Formation Session Officielle JCI Presenter", organizer:"JCI Bardo", place:"Le Bardo", date:"21 Mai, 2023", img:"./assets/img/programmes/formationsetforums/jci-presenter.jpg", description:"\"𝑬𝒕𝒓𝒆 𝒑𝒍𝒖𝒔 𝒑𝒆𝒓𝒄𝒖𝒕𝒂𝒏𝒕 𝒍𝒐𝒓𝒔 𝒅𝒆 𝒍𝒂 𝒓́𝒂𝒍𝒊𝒔𝒂𝒕𝒊𝒐𝒏 𝒅\'𝒖𝒏𝒆 𝒑𝒓́𝒔𝒆𝒏𝒕𝒂𝒕𝒊𝒐𝒏 𝒆𝒏 𝒑𝒖𝒃𝒍𝒊𝒄 𝒆𝒔𝒕\n𝒅́𝒋̀ 𝒍𝒂 𝒎𝒐𝒊𝒕𝒊́ 𝒅𝒖 𝒄𝒉𝒆𝒎𝒊𝒏\"\nDans ce cadre, la Jeune Chambre économique du Bardo a organisé,\nle 21 mais 2023, la session officielle intitulée \"𝐉𝐂𝐈 𝐏𝐫𝐞𝐬𝐞𝐧𝐭𝐞𝐫\" au\nCentre Integré de la Jeunesse et de l\'Enfance Le Bardo.\nLa formation traitera les thèmes suivants :\nOrganiser un message pour le rendre impactant.\nApprendre plusieurs techniques pour marquer les esprits lors de\nl\'intervention à l\'orale et plusieurs manières de convaincre\ndéfinitivement l'auditoire.\n\nCette journée de 12 heures de travail intense est animée par nos très\nchers formateurs\n\" Insaf Ayari\" \" الورتتاني سيرين \" et \" Wissem Sammoud \""},
        {id:"communicationdansolm", titre:"Formation La Communication dans l'OLM", organizer:"JCI Bardo", place:"Le Bardo", date:"30 Avril, 2023", img:"./assets/img/programmes/formationsetforums/la-communication-dans-olm.jpg", description:"Formation \"La Communication dans l\'OLM \"\norganisée par la jeune chambre économique du\nbardo le 30 Avril 2023, au Centre Integré de la\nJeunesse et de l'Enfance Le Bardo , animée par\nnos chers formateurs Wissem Sammoud et Cyrine Ouertateni.\n\nLe but de cette formation est de mieux\ncomprendre la communication dans l\'OLM, le\nrôle du parrain et marraine, les erreurs à éviter dans la communication."},
        {id:"ellama", titre:"اللمة", organizer:"JCIs", place:"Médina de Tunis", date:"17 Avril, 2023", img:"./assets/img/programmes/formationsetforums/lama.jpg", description:"Forum national organisé par les jeunes chambres\néconomiques Bardo, Bekalta,El Manar, El battan,\nFrance Ville, Fouchena, Gafsa, Isi Ariana\n,Khaznadar ,Ksar Hlel, Kairoun, Leaders Beb Souika, La Goulette et Kram, Menzel Bourguiba,\nMahdia, Metline, Menzel Abdrahmen, Menzel Hor, Metlaoui, Morneguia, Morneg,\n\nSbikha,Sejnane Tozeur, Zaghouan El Medina,\nZaghouan et Zahrouni\n\nintitulé \"Ramadan Progress\" au mois du Ramadan\nen ligne sur le plateforme Discord."},
        {id:"ramadanprogress", titre:"Ramadan Progress", organizer:"JCIs", place:"sur Discord", date:"Mois de Ramadan", img:"./assets/img/programmes/formationsetforums/ramadan-progress.jpg", description:""},
        {id:"academiedesmembres", titre:"Académie des membres", organizer:"JCIs", place:"Municipalité de Ben Arous", date:"12 Mars, 2023", img:"./assets/img/programmes/formationsetforums/academie-des-membres.jpg", description:""},
        {id:"jayceespath", titre:"Formation Jaycee's Path", organizer:"JCI Bardo", place:"Le Bardo", date:"26 Février, 2023", img:"./assets/img/programmes/formationsetforums/jaycees-path.jpg", description:"Retour en images sur le journée de formation \"JAYCEES Path\"  organisée par la jeune chambre économique du bardo le 26 février 2023, à la municipalité du bardo, animée par nos chers formateurs Alla Eddine Rezgui, Wissem Sammoud et Cyrine Ouertateni.\n\nLe but de cette formation est de mieux comprendre l'historique , le mission et la vision de la JCI, les activités afin que les membres puissent comprendre leur parcours dans l\'organisation.\n\nDurant cette formation on a été honoré par la présence de :\nnotre cher Président national : Mourad Hidri\nCher VPE de la Zone A Ons Meftahi\nCher Conseiller du protocole de la zone A : Oussema Ben Ali Ferjani\n\nPendant la formation, nous étions surpris par la visite de l\'animateur de télévision Elhiwar Ettounsi et le journaliste Sami Bennour ."}
      ]
    }
]

const blogs: {
  id: string;
  titre: string;
  organizer: string;
  place: string;
  date: string;
  img: string;
  description: string;
}[] = [
  {id:"letstalkglobally", titre:"Let’s Talk Globally : Second Week", organizer:"JCI Aleppo", place:"sur Google Meet", date:"", img:"./assets/img/detail/glob2.jpg", description:"أقلعت طائرتنا الإلكترونية في اسبوعها الثاني و ذلك يوم 28 اوت 2023 على الساعة السادسة مساءاً بتوقيت تونس في رحلة عبر الحدود تم التعرف من خلالها على العادات والتقاليد التي تمثل هويّة كل دولة من الدول المشاركة في المنتدى العالمي\" let's talk Globally \" الذي انتظم على منصة Google Meet بالشراكة مع: الغرفة الفتية الدولية حلب (سورية) -الغرفة الفتية الدولية باردو (تونس) - الغرفة الفتية الدولية السويداء (سورية) - الغرفة الفتية الدولية طرطوس (سورية) - الغرفة الفتية الدولية فيلا ماريا (الأرجنتين) -الغرفة الفتية الدولية مانشستر (بريطانيا) - الغرفة الفتية الدولية مراكش(المغرب)-الغرفة الفتية الاقتصادية لوزاكا ( زمبيا). كانت  خطوة  ممتعة في رحلتنا، تعرفنا من خلالها على أعضاء جدد من غرف فتية أخرى حول العالم لاكتساب العلاقات وتكوين الصداقات العالمية، بالإضافة ا التعرف على الدول و ثقافاتها و لمواصلة بقية رحلتنا المشوقة، تدعودكم الغرفة الفتية العالمية بباردو لمتابعتنا في Let\'s Talk Globally لإكتشاف المزيد من الحضارات و الثقافات لتعزيز التعاون الدولي بين غرفنا المحلية"},
  {id:"ecoverteearthforum", titre:"Resilient Earth Forum", organizer:"", place:"", date:"", img:"./assets/img/detail/eco-v.jpg", description:"Dans le cadre de son projet \"Éco-verte 2.0\"\n𝗟a Jeune 𝗖hambre 𝗘conomique du 𝗕ardo à organisé, 𝐥𝐞 18 𝐀𝐨𝐮̂𝐭 2023 𝐚̀ 14H au 𝐂𝐥𝐮𝐛'𝐲 𝐥𝐞 𝐁𝐚𝐫𝐝𝐨 , en partenariat avec le mouvement Youth For Climate Tunisia - Community\n\" 𝐑𝐄𝐒𝐈𝐋𝐈𝐄𝐍𝐓 𝐄𝐀𝐑𝐓𝐇 𝐅𝐎𝐑𝐔𝐌 \"\nLa journée s'est ouverte avec la projection du film \" 𝐓𝐡𝐞 11𝐭𝐡 𝐇𝐨𝐮𝐫 𝐫𝐢𝐠𝐡𝐭 \" qui a été suivie par une table ronde où les enjeux environnementaux abordés par le film ont été  discutés.\nNous avons fini notre forum par une séance de cours de calligraphie arabe.\nOn tient à remercier sincèrement club\'y bardo pour l\'aimable accueil ainsi que nos partenaires,\nNous tenons également à remercier nos chers membres pour leurs participation active à cette journée."},
  {id:"microsoft1", titre:"Formation Microsoft by JCI", organizer:"", place:"", date:"", img:"./assets/img/detail/formation-micrsoft.jpg", description:"\"La formation est l\'essence de tout succès\"\nRetour en images sur le forum intitulé \" Microsoft by JCI\" qui a eu lieu le 15,17,18 Août 2023 sur Google Meet, en collaboration avec INJAZ Tunisia  et organisé par Bardo, JCI OLM Oued Ellil, JCI Tebourba, JCI jedaida, JCI France Ville , JCI El Battan , JCI Les Jardins, JCI La Marsa, JCI IBN Khaldoun , JCI Leaders Beb Souika , JCI  OLM  Manouba , JCI nouvelle medina , JCI Mornaguia.\nCe forum a visé le programme de Microsoft  qui est spécialement dédié aux membres de la JCI qui veulent acquérir de nouvelles compétences professionnelles.\nElle couvre tous les outils indispensables pour travailler efficacement : Word, Excel, PowerPoint, Outlook..\nanimé par nos chers formateurs سيرين الورتتاني  et Wissem Sammoud\nOn tient vivement à les remercier pour leur professionnalisme.\nOn a été honoré par l\'intervention de notre vpf de la zone A dans la journée de l\'ouverture,\nNous tenons également à remercier nos chers participants pour leur engagement et leur confiance."},
  {id:"projectmanagement", titre:"Formation Project Management", organizer:"", place:"", date:"", img:"./assets/img/detail/proj-mang.jpg", description:"Retour en images sur la session recommandé intitulée \" 𝐏𝐫𝐨𝐣𝐞𝐜𝐭 𝐌𝐚𝐧𝐚𝐠𝐞𝐦𝐞𝐧𝐭 \" qui a eu lieu 𝑫𝒊𝒎𝒂𝒏𝒄𝒉𝒆 13 𝑨𝒐𝒖𝒕 2023 à la 𝑴𝒖𝒏𝒊𝒄𝒊𝒑𝒂𝒍𝒊𝒕𝒆́ 𝒅𝒖 𝑩𝒂𝒓𝒅𝒐 , animée par nos chers formateurs 𝑵𝒂𝒔𝒔𝒆𝒓𝒆𝒅𝒅𝒊𝒏 𝑴𝒆𝒄𝒉𝒓𝒊 et 𝑪𝒚𝒓𝒊𝒏𝒆 𝑶𝒖𝒆𝒓𝒕𝒂𝒕𝒆𝒏𝒊 qu'on tient par cette occasion à les remercier pour leurs professionnalisme et leurs efforts déployés.\nSans oublier de remercier nos chers membres pour leurs engagements pour faire réussir le déroulement de la formation."},
  {id:"radionesrine", titre:"Passage Radio", organizer:"", place:"", date:"", img:"./assets/img/detail/pass-nesr.jpg", description:"Soyez à l'écoute du passage radio de notre Secrétaire Général de la jeune chambre économique de Bardo \" Nesrin Medini  \" sur les ondes de Radio Jeunes Tunisie (Page officielle) à 11h pour parler sur notre Forum international : \" Let\'s Talk Globally\"."},
  {id:"letstalkglobally1", titre:"Let’s Talk Globally", organizer:"JCI Aleppo", place:"sur Google Meet", date:"", img:"./assets/img/detail/glob1.jpg", description:"هل أنتم جاهزون لرحلة حول العالم وانتم خلف شاشاتكم؟!\n من منّا لم يحلم يوماً بالسفر حول العالم للتعرّف على جميع الأماكن الجميلة فيه؟ من منّا لم يرغب في تجربة التعرّف على ثقافات وعادات وتقاليد الناس؟\n من هنا أتت فكرة Let\’s Talk Globally لنتمكّن من تجربة الثقافات الأخرى دون حتى الحاجة إلى مغادرة بيوتنا!\n حيث ترتكز الفكرة الأساسية في استخدام الانترنت كوسيلة لاختصار المسافات بين الناس عن طريق إقامة عدة جلسات بين كل من:\n الغرفة الفتية الدولية حلب (سورية) -الغرفة الفتية الدولية باردو (تونس) - الغرفة الفتية الدولية السويداء (سورية) - الغرفة الفتية الدولية طرطوس (سورية) - الغرفة الفتية الدولية فيلا ماريا (الأرجنتين) -الغرفة الفتية الدولية مانشستر (بريطانيا) - الغرفة الفتية الدولية مراكش(المغرب).\n تقدم كل غرفة فيها عرضاً تقديمياً في جلسة يتحدث فيها المشاركون فيها الأصدقاء عن الموسيقى في بلدهم، العادات والتقاليد في المناسبات الرسميّة، الأطعمة الشهيرة لديهم، أهم الأماكن الأثرية والسياحية والدينية، بالإضافة الى التعرف على بعضهم البعض وخلق روابط الصلة المتينة والتعرف على صورة البلد وأهله بشكل أفضل كأنك قمت بزيارته وأنت جالس في المنزل مع تصحيح بعض الصور النمطيّة عن البلدان المشاركة.\nAre you ready for a trip worldwide, and you\'re behind your screens?\nWho never dreamed of traveling the world to learn about all the beautiful places in it? Who wanted to experience something other than learning about people\'s cultures, customs, and traditions?\nTherefore the idea of Let\'s Talk Globally is to experience other cultures without leaving our homes!\nThe basic idea is to use the Internet as a means of shortening people\'s distances by holding several sessions between:\nJCI Aleppo   الغرفة الفتية الدولية حلب (Syria) - JCI Bardo(Tunisia) - JCI Lusaka (Zambia) - JCI Marrakech (Morocco) - JCI Manchester JCI(UK) - JCI Sweida   الغرفة الفتية الدولية السويداء (Syria) - JCI Tartus (Syria) - JCI Villa María (Argentina).\nEach Organization presents a presentation at a session where friends talk about music in their country, habits, and traditions at official events, their famous foods, and the most important archaeological, tourist, and religious places, In addition to getting to know each other and creating strong links and better familiarize yourself with the image of the country and its people as if you had visited it while sitting at home while correcting some stereotypes about the participating countries.\nJCI BARDO JCI Lusaka JCI Tartus JCI Villa María JCI Manchester JCI Sweida   الغرفة الفتية الدولية السويداء JCI Marrakech"},
  {id:"cafetalkpsychologie", titre:"Cafe Talk : Psychologie", organizer:"", place:"", date:"", img:"./assets/img/detail/cafe-talk.jpg", description:"Retour en images sur le Café Talk sous le thème \" Café Talk... هيا نحكيو Psychologie   \" qui a eu lieu 𝐒𝐚𝐦𝐞𝐝𝐢 5 𝐀𝐨𝐮̂𝐭  2023 dans 𝐥𝐞 𝐜𝐚𝐟𝐞́ 𝐁𝐨𝐧𝐳𝐚𝐢 𝐁𝐚𝐫𝐝𝐨. \nLe café talk a été animée  par l'intervention de nos chers psychologues 𝐌𝐚𝐫𝐚𝐦 𝐃𝐨𝐠𝐡𝐫𝐢  et 𝐑𝐚𝐡𝐦𝐚 𝐂𝐡𝐚𝐢𝐛𝐢 , qui ont partagé leurs connaissances et leurs expériences pour permettre aux membres de connaître les maladies mentales, résoudre les difficultés d’ordre psychique . \npar cette occasion, On tient à les remercier pour leurs professionalismes et leurs soutiens psychologiques . \nSans oublier de remercier nos chers membres pour leurs engagements."},
  {id:"canadianresume", titre:"Formation the A B C’s of a Canadian Resume", organizer:"", place:"", date:"", img:"./assets/img/detail/formation.jpg", description:"Retour en images sur la session officielle intitulée \" 𝐓𝐡𝐞 𝐀𝐁𝐂\'𝐬 𝐨𝐟 𝐚 𝐂𝐚𝐧𝐚𝐝𝐢𝐚𝐧 𝐑𝐞𝐬𝐮𝐦𝐞  \" qui a eu lieu 𝐌𝐞𝐫𝐜𝐫𝐞𝐝𝐢 2 𝐀𝐨𝐮̂𝐭  2023 sur 𝐆𝐨𝐨𝐠𝐥𝐞 𝐌𝐞𝐞𝐭 . \nCette Formation a été animée animée par notre chére Formatrice 𝐘𝐨𝐬𝐫𝐚 𝐁𝐞𝐧 𝐀𝐛𝐝𝐚𝐥𝐥𝐚𝐡 ,\nqui a partagé ses connaissances et son expérience pour permettre aux membres de connaître les types de Resume le plus répandues, les parties d\'un résumé, les caractéristiques d\'un Cv canadien et les erreurs à éviter. \npar cette occasion, on tient à  remercier notre chère formatrice pour leur professionnalisme et leur efforts tous au long de la formation. \nSans oublier de remercier nos chers membres pour leurs engagements pour faire réussir le déroulement de la formation."},
  {id:"radionoor", titre:"Passage Radio", organizer:"", place:"", date:"", img:"./assets/img/detail/passa-nour.jpg", description:"Soyez à l'écoute du passage radio de notre présidente de la jeune chambre économique de Bardo \" Noor Ben Ammar \" sur les ondes de Radio Express FM à 8:30 pour parler sur le mini salon : \" Journée des enseignants organisé par Bureau de l\'Emploi et du Travail Indépendant de Bardo✨"},
  {id:"olmplusefficace", titre:"Récompense OLM la plus Efficace de la zone A", organizer:"", place:"", date:"", img:"./assets/img/detail/gold.jpg", description:"𝐎𝐋𝐌 𝐋𝐀 𝐏𝐋𝐔𝐒 𝐄𝐅𝐅𝐈𝐂𝐀𝐂𝐄 : 𝐏𝐑𝐈𝐗 𝐆𝐎𝐋𝐃\nLa 𝔍eune ℭhambre 𝔈conomique du Bardo a remporté une récompense prestigieuse pour la deuxième fois consécutive, se plaçant ainsi au sommet du classement d\'une 1ère place au sein du programme de 100% efficacité.\nCette reconnaissance exceptionnelle a été décernée à la JCI Bardo lors de l\'occasion spéciale de 𝗹𝗮 2ème 𝗿é𝘂𝗻𝗶𝗼𝗻 𝘇𝗼𝗻𝗮𝗹𝗲 𝗱𝗲𝘀 𝗽𝗿é𝘀𝗶𝗱𝗲𝗻𝘁𝘀 d\'où les représentants des OLM se sont réunis pour partager leurs réalisations et célébrer les succès collectifs.\n\nLa JCI Bardo a brillé par son engagement indéfectible envers l\'efficacité et la réalisation de résultats concrets. Grâce à son approche méthodique et à la passion de ses membres , cette performance remarquable témoigne l\'engagement continu de la JCI Bardo à apporter des changements positifs et durables dans sa communauté.✨✨"},
]

const recents: {
  id: string;
  titre: string;
  img: string;
}[] = [
  {id:"#journeeinformation", titre:"Participation à la journée d'information", img:"./assets/img/grid/journée-information.jpg"},
  {id:"#jcipresenter", titre:"Formation Session Officielle JCI Presenter", img:"./assets/img/programmes/formationsetforums/jci presenter.jpg"},
  {id:"#santesexuelle", titre:"Journée sensibilisation sur la santé sexuelle et reproductive", img:"./assets/img/programmes/projetslocaux/sensibilisation.jpg"}
]

const carouselItems : {
  img: string;
  title: string;
}[] =  [
  {img:'./assets/img/partenaires/bayrem.jpg', title:"Lycée Bayrem Tounsi"},
  {img:'./assets/img/partenaires/centre.jpg', title:"Centre Integré de Jeunesse et d'Enfance Bardo"},
  {img:'./assets/img/partenaires/injaz.jpg', title:"INJAZ Tunis"},
  {img:'./assets/img/partenaires/youth.jpg', title:"YOUTH FOR CLIMATE Tunisia"},
  {img:'./assets/img/partenaires/jeune.png', title:"Maison de Jeunesse Khaznadar"},
  {img:'./assets/img/partenaires/cluby.jpg', title:"Club'y"},
  {img:'./assets/img/partenaires/iri.jpg', title:"International Republican Institut"},
  {img:'./assets/img/partenaires/nt.jpg', title:"Nextun Agency"},
  {img:'./assets/img/partenaires/femme.jpg', title:"Association des Femmes Arabes Spécialisées"},
  {img:'./assets/img/partenaires/saad.jpg', title:"Institut Saad"},
  {img:'./assets/img/partenaires/aneti.png', title:"ANETI Bardo"},
  {img:'./assets/img/partenaires/himo.jpg', title:"Association Tunisienne de l'Hémophilie"},
  {img:'./assets/img/partenaires/biblio.jpg', title:"Bibliothèque Publique du Bardo"},
  {img:'./assets/img/partenaires/municipalitebardo.png', title:"Municipalité du Bardo"}
];

export { projets, blogs, recents, carouselItems };