import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-blogdetail',
  templateUrl: './blogdetail.component.html',
  styleUrls: ['./blogdetail.component.css']
})
export class BlogdetailComponent implements OnInit {

  blogs = [
    {id:"charity", img:'./assets/img/detail/charity-day.jpg', text:"\"𝙇𝙖 charité 𝙚𝙨𝙩 𝙡𝙖 clé 𝙦𝙪𝙞 𝙤𝙪𝙫𝙧𝙚 𝙡𝙚 𝙘𝙤𝙚𝙪𝙧 𝙙𝙚𝙨 𝙖𝙪𝙩𝙧𝙚𝙨.\"\nLe 5 septembre, depuis 2012, le monde célébre 𝙡𝙖 𝙟𝙤𝙪𝙧𝙣𝙚́𝙚 𝙙𝙚 𝙡𝙖 𝙘𝙝𝙖𝙧𝙞𝙩𝙚́ pour sensibiliser et promouvoir l\'importance de la solidarité et de l\'aide aux personnes dans le besoin à travers le monde.\nCette journée est soutenue par 𝙡𝙖 𝙅𝙚𝙪𝙣𝙚 𝘾𝙝𝙖𝙢𝙗𝙧𝙚 𝙄𝙣𝙩𝙚𝙧𝙣𝙖𝙩𝙞𝙤𝙣𝙖𝙡𝙚 𝙙𝙪 𝘽𝙖𝙧𝙙𝙤  à laquelle vous encourage à s\'engager dans des actions charitables pour contribuer à créer un monde meilleur et plus équitable."},
    {id:"letstalkglobally", img:'./assets/img/detail/glob2.jpg', text:"أقلعت طائرتنا الإلكترونية في اسبوعها الثاني و ذلك يوم 28 اوت 2023 على الساعة السادسة مساءاً بتوقيت تونس في رحلة عبر الحدود تم التعرف من خلالها على العادات والتقاليد التي تمثل هويّة كل دولة من الدول المشاركة في المنتدى العالمي\" let's talk Globally \" الذي انتظم على منصة Google Meet بالشراكة مع: الغرفة الفتية الدولية حلب (سورية) -الغرفة الفتية الدولية باردو (تونس) - الغرفة الفتية الدولية السويداء (سورية) - الغرفة الفتية الدولية طرطوس (سورية) - الغرفة الفتية الدولية فيلا ماريا (الأرجنتين) -الغرفة الفتية الدولية مانشستر (بريطانيا) - الغرفة الفتية الدولية مراكش(المغرب)-الغرفة الفتية الاقتصادية لوزاكا ( زمبيا). كانت  خطوة  ممتعة في رحلتنا، تعرفنا من خلالها على أعضاء جدد من غرف فتية أخرى حول العالم لاكتساب العلاقات وتكوين الصداقات العالمية، بالإضافة ا التعرف على الدول و ثقافاتها و لمواصلة بقية رحلتنا المشوقة، تدعودكم الغرفة الفتية العالمية بباردو لمتابعتنا في Let\'s Talk Globally لإكتشاف المزيد من الحضارات و الثقافات لتعزيز التعاون الدولي بين غرفنا المحلية"},
    {id:"ecovert2", img:'./assets/img/detail/eco-v.jpg', text:"Dans le cadre de son projet \"Éco-verte 2.0\"\n𝗟a Jeune 𝗖hambre 𝗘conomique du 𝗕ardo à organisé, 𝐥𝐞 18 𝐀𝐨𝐮̂𝐭 2023 𝐚̀ 14H au 𝐂𝐥𝐮𝐛'𝐲 𝐥𝐞 𝐁𝐚𝐫𝐝𝐨 , en partenariat avec le mouvement Youth For Climate Tunisia - Community\n\" 𝐑𝐄𝐒𝐈𝐋𝐈𝐄𝐍𝐓 𝐄𝐀𝐑𝐓𝐇 𝐅𝐎𝐑𝐔𝐌 \"\nLa journée s'est ouverte avec la projection du film \" 𝐓𝐡𝐞 11𝐭𝐡 𝐇𝐨𝐮𝐫 𝐫𝐢𝐠𝐡𝐭 \" qui a été suivie par une table ronde où les enjeux environnementaux abordés par le film ont été  discutés.\nNous avons fini notre forum par une séance de cours de calligraphie arabe.\nOn tient à remercier sincèrement club\'y bardo pour l\'aimable accueil ainsi que nos partenaires,\nNous tenons également à remercier nos chers membres pour leurs participation active à cette journée."},
    {id:"microsoft", img:'./assets/img/detail/formation-micrsoft.jpg', text:"\"La formation est l\'essence de tout succès\"\nRetour en images sur le forum intitulé \" Microsoft by JCI\" qui a eu lieu le 15,17,18 Août 2023 sur Google Meet, en collaboration avec INJAZ Tunisia  et organisé par Bardo, JCI OLM Oued Ellil, JCI Tebourba, JCI jedaida, JCI France Ville , JCI El Battan , JCI Les Jardins, JCI La Marsa, JCI IBN Khaldoun , JCI Leaders Beb Souika , JCI  OLM  Manouba , JCI nouvelle medina , JCI Mornaguia.\nCe forum a visé le programme de Microsoft  qui est spécialement dédié aux membres de la JCI qui veulent acquérir de nouvelles compétences professionnelles.\nElle couvre tous les outils indispensables pour travailler efficacement : Word, Excel, PowerPoint, Outlook..\nanimé par nos chers formateurs سيرين الورتتاني  et Wissem Sammoud\nOn tient vivement à les remercier pour leur professionnalisme.\nOn a été honoré par l\'intervention de notre vpf de la zone A dans la journée de l\'ouverture,\nNous tenons également à remercier nos chers participants pour leur engagement et leur confiance."},
    {id:"sponsor2", img:'./assets/img/detail/sponsor2.jpg', text:"La 𝕵eune 𝕮hambre 𝕰conomique du 𝕭𝖆𝖗𝖉𝖔 tient à remercier sincèrement son cher 𝘀𝗽𝗼𝗻𝘀𝗼𝗿 IMYAS pour sa généreuse contribution, à l’occasion de notre formation recommandé intitulée \" Project Management \" qui a eu lieu le 13 Août 2023.\nGrâce à sa présence , l\’organisation s\’est déroulée dans des conditions optimales.\nNous sommes particulièrement reconnaissants à son soutien dans notre noble cause.\nSon aide nous permettra de mener à bien notre mission .\nNous espérons avoir l\'occasion de travailler de nouveau avec vous à l\'avenir."},
    {id:"projectmanagement", img:'./assets/img/detail/proj-mang.jpg', text:"Retour en images sur la session recommandé intitulée \" 𝐏𝐫𝐨𝐣𝐞𝐜𝐭 𝐌𝐚𝐧𝐚𝐠𝐞𝐦𝐞𝐧𝐭 \" qui a eu lieu 𝑫𝒊𝒎𝒂𝒏𝒄𝒉𝒆 13 𝑨𝒐𝒖𝒕 2023 à la 𝑴𝒖𝒏𝒊𝒄𝒊𝒑𝒂𝒍𝒊𝒕𝒆́ 𝒅𝒖 𝑩𝒂𝒓𝒅𝒐 , animée par nos chers formateurs 𝑵𝒂𝒔𝒔𝒆𝒓𝒆𝒅𝒅𝒊𝒏 𝑴𝒆𝒄𝒉𝒓𝒊 et 𝑪𝒚𝒓𝒊𝒏𝒆 𝑶𝒖𝒆𝒓𝒕𝒂𝒕𝒆𝒏𝒊 qu'on tient par cette occasion à les remercier pour leurs professionnalisme et leurs efforts déployés.\nSans oublier de remercier nos chers membres pour leurs engagements pour faire réussir le déroulement de la formation."},
    {id:"womansday", img:'./assets/img/detail/woman\'s-day.jpg', text:"Le 13 août anniversaire du code du statut personnel devenu \" la fête nationale de la femme \".\nCette journée est l\'occasion chaque année pour rendre hommage au mouvement en faveur des droits des femmes et à affirmer avec fierté et certitude le principe de l\'égalité entre les femmes et les hommes.\nDe ce fait la Jeune Chambre internationale économique du Bardo tient à encourager les efforts entrepris par les institutions et les ONG pour favoriser l\'autonomie des femmes en vue de relever les défis sociaux, économique et politiques dans la Tunisie et à dans le monde entier."},
    {id:"youthday", img:'./assets/img/detail/youth-day.jpg', text:"La jeunesse est plus apte à inventer qu'à juger, à exécuter qu'à conseiller, à lancer des projets nouveaux qu'à poursuivre des anciens. \”\nLe 12 août a été désigné par l\’Organisation des nations unies (ONU) comme étant la Journée internationale de la jeunesse, qui à son tour constitue une célébration annuelle du rôle des jeunes en tant que partenaires essentiels du changement et sensibiliser sur les défis et problèmes auxquels ils sont confrontés.\nÀ cette occasion La jeune Chambre Internationale de Bardo , tient à féliciter tous les jeunes du monde , spécialement ses membres\" pour leur énergie, leur créativité et leur engagement envers un avenir meilleur.Continuez à poursuivre vos rêves et à contribuer à la société de manière significative. Joyeuse Journée de la Jeunesse ! 🌟\n\" La Jeunesse est un ART \"\nContinuez à inspirer ❤️"},
    {id:"radionesrine", img:'./assets/img/detail/pass-nesr.jpg', text:"Soyez à l'écoute du passage radio de notre Secrétaire Général de la jeune chambre économique de Bardo \" Nesrin Medini  \" sur les ondes de Radio Jeunes Tunisie (Page officielle) à 11h pour parler sur notre Forum international : \" Let\'s Talk Globally\"."},
    {id:"letstalkglobally1", img:'./assets/img/detail/glob1.jpg', text:"هل أنتم جاهزون لرحلة حول العالم وانتم خلف شاشاتكم؟!\n من منّا لم يحلم يوماً بالسفر حول العالم للتعرّف على جميع الأماكن الجميلة فيه؟ من منّا لم يرغب في تجربة التعرّف على ثقافات وعادات وتقاليد الناس؟\n من هنا أتت فكرة Let\’s Talk Globally لنتمكّن من تجربة الثقافات الأخرى دون حتى الحاجة إلى مغادرة بيوتنا!\n حيث ترتكز الفكرة الأساسية في استخدام الانترنت كوسيلة لاختصار المسافات بين الناس عن طريق إقامة عدة جلسات بين كل من:\n الغرفة الفتية الدولية حلب (سورية) -الغرفة الفتية الدولية باردو (تونس) - الغرفة الفتية الدولية السويداء (سورية) - الغرفة الفتية الدولية طرطوس (سورية) - الغرفة الفتية الدولية فيلا ماريا (الأرجنتين) -الغرفة الفتية الدولية مانشستر (بريطانيا) - الغرفة الفتية الدولية مراكش(المغرب).\n تقدم كل غرفة فيها عرضاً تقديمياً في جلسة يتحدث فيها المشاركون فيها الأصدقاء عن الموسيقى في بلدهم، العادات والتقاليد في المناسبات الرسميّة، الأطعمة الشهيرة لديهم، أهم الأماكن الأثرية والسياحية والدينية، بالإضافة الى التعرف على بعضهم البعض وخلق روابط الصلة المتينة والتعرف على صورة البلد وأهله بشكل أفضل كأنك قمت بزيارته وأنت جالس في المنزل مع تصحيح بعض الصور النمطيّة عن البلدان المشاركة.\nAre you ready for a trip worldwide, and you\'re behind your screens?\nWho never dreamed of traveling the world to learn about all the beautiful places in it? Who wanted to experience something other than learning about people\'s cultures, customs, and traditions?\nTherefore the idea of Let\'s Talk Globally is to experience other cultures without leaving our homes!\nThe basic idea is to use the Internet as a means of shortening people\'s distances by holding several sessions between:\nJCI Aleppo   الغرفة الفتية الدولية حلب (Syria) - JCI Bardo(Tunisia) - JCI Lusaka (Zambia) - JCI Marrakech (Morocco) - JCI Manchester JCI(UK) - JCI Sweida   الغرفة الفتية الدولية السويداء (Syria) - JCI Tartus (Syria) - JCI Villa María (Argentina).\nEach Organization presents a presentation at a session where friends talk about music in their country, habits, and traditions at official events, their famous foods, and the most important archaeological, tourist, and religious places, In addition to getting to know each other and creating strong links and better familiarize yourself with the image of the country and its people as if you had visited it while sitting at home while correcting some stereotypes about the participating countries.\nJCI BARDO JCI Lusaka JCI Tartus JCI Villa María JCI Manchester JCI Sweida   الغرفة الفتية الدولية السويداء JCI Marrakech"},
    {id:"sponsor1", img:'./assets/img/detail/sponsor1.jpg', text:"La 𝕵eune 𝕮hambre 𝕰conomique du 𝕭𝖆𝖗𝖉𝖔 tient à remercier sincèrement son cher 𝘀𝗽𝗼𝗻𝘀𝗼𝗿 Box Store  pour sa généreuse contribution, à l\’occasion de notre café talk intitulée \" هيا نحكيو psychologie\" qui a eu lieu le 5 Août 2023. \nGrâce à sa présence , l\’organisation s\’est déroulée dans des conditions optimales. \nNous sommes particulièrement reconnaissants à son soutien dans notre noble cause. \nSon aide nous permettra de mener à bien notre mission . \nNous espérons avoir l\'occasion de travailler de nouveau avec vous à l\'avenir."},
    {id:"diversity", img:'./assets/img/detail/diversité.jpg', text:"𝙎𝙤𝙪𝙩𝙚𝙣𝙤𝙣𝙨 𝙡𝙖 𝙙𝙞𝙫𝙚𝙧𝙨𝙞𝙩é 𝙘𝙪𝙡𝙩𝙪𝙧𝙚𝙡𝙡𝙚 𝙚𝙩 𝙡𝙚𝙨 𝙙𝙧𝙤𝙞𝙩𝙨 𝙙𝙚𝙨 𝙥𝙚𝙪𝙥𝙡𝙚𝙨 𝙖𝙪𝙩𝙤𝙘𝙝𝙩𝙤𝙣𝙚𝙨 !\nEn cette journée internationale dédiée à la reconnaissance de leurs héritages, la 🇯 𝗲𝘂𝗻𝗲 🇨 𝗵𝗮𝗺𝗯𝗿𝗲 🇮 𝗻𝘁𝗲𝗿𝗻𝗮𝘁𝗶𝗼𝗻𝗮𝗹𝗲 𝗱𝘂 𝗕𝗮𝗿𝗱𝗼 célèbre la richesse culturelle et la contribution inestimable des 𝐩𝐞𝐮𝐩𝐥𝐞𝐬 𝐚𝐮𝐭𝐨𝐜𝐡𝐭𝐨𝐧𝐞𝐬 à notre monde le 9 août de chaque année.\nEnsemble, œuvrons pour la préservation de leurs traditions ancestrales, le respect de leurs droits fondamentaux et l\'harmonie entre les peuples. Unis dans la diversité, agissons pour un avenir inclusif où chaque voix et culture compte."},
    {id:"cafetalk", img:'./assets/img/detail/cafe-talk.jpg', text:"Retour en images sur le Café Talk sous le thème \" Café Talk... هيا نحكيو Psychologie   \" qui a eu lieu 𝐒𝐚𝐦𝐞𝐝𝐢 5 𝐀𝐨𝐮̂𝐭  2023 dans 𝐥𝐞 𝐜𝐚𝐟𝐞́ 𝐁𝐨𝐧𝐳𝐚𝐢 𝐁𝐚𝐫𝐝𝐨. \nLe café talk a été animée  par l'intervention de nos chers psychologues 𝐌𝐚𝐫𝐚𝐦 𝐃𝐨𝐠𝐡𝐫𝐢  et 𝐑𝐚𝐡𝐦𝐚 𝐂𝐡𝐚𝐢𝐛𝐢 , qui ont partagé leurs connaissances et leurs expériences pour permettre aux membres de connaître les maladies mentales, résoudre les difficultés d’ordre psychique . \npar cette occasion, On tient à les remercier pour leurs professionalismes et leurs soutiens psychologiques . \nSans oublier de remercier nos chers membres pour leurs engagements."},
    {id:"canadienresume", img:'./assets/img/detail/formation.jpg', text:"Retour en images sur la session officielle intitulée \" 𝐓𝐡𝐞 𝐀𝐁𝐂\'𝐬 𝐨𝐟 𝐚 𝐂𝐚𝐧𝐚𝐝𝐢𝐚𝐧 𝐑𝐞𝐬𝐮𝐦𝐞  \" qui a eu lieu 𝐌𝐞𝐫𝐜𝐫𝐞𝐝𝐢 2 𝐀𝐨𝐮̂𝐭  2023 sur 𝐆𝐨𝐨𝐠𝐥𝐞 𝐌𝐞𝐞𝐭 . \nCette Formation a été animée animée par notre chére Formatrice 𝐘𝐨𝐬𝐫𝐚 𝐁𝐞𝐧 𝐀𝐛𝐝𝐚𝐥𝐥𝐚𝐡 ,\nqui a partagé ses connaissances et son expérience pour permettre aux membres de connaître les types de Resume le plus répandues, les parties d\'un résumé, les caractéristiques d\'un Cv canadien et les erreurs à éviter. \npar cette occasion, on tient à  remercier notre chère formatrice pour leur professionnalisme et leur efforts tous au long de la formation. \nSans oublier de remercier nos chers membres pour leurs engagements pour faire réussir le déroulement de la formation."},
    {id:"radionoor", img:'./assets/img/detail/passa-nour.jpg', text:"Soyez à l'écoute du passage radio de notre présidente de la jeune chambre économique de Bardo \" Noor Ben Ammar \" sur les ondes de Radio Express FM à 8:30 pour parler sur le mini salon : \" Journée des enseignants organisé par Bureau de l\'Emploi et du Travail Indépendant de Bardo✨"},
    {id:"olmplusefficace", img:'./assets/img/detail/gold.jpg', text:"𝐎𝐋𝐌 𝐋𝐀 𝐏𝐋𝐔𝐒 𝐄𝐅𝐅𝐈𝐂𝐀𝐂𝐄 : 𝐏𝐑𝐈𝐗 𝐆𝐎𝐋𝐃\nLa 𝔍eune ℭhambre 𝔈conomique du Bardo a remporté une récompense prestigieuse pour la deuxième fois consécutive, se plaçant ainsi au sommet du classement d\'une 1ère place au sein du programme de 100% efficacité.\nCette reconnaissance exceptionnelle a été décernée à la JCI Bardo lors de l\'occasion spéciale de 𝗹𝗮 2ème 𝗿é𝘂𝗻𝗶𝗼𝗻 𝘇𝗼𝗻𝗮𝗹𝗲 𝗱𝗲𝘀 𝗽𝗿é𝘀𝗶𝗱𝗲𝗻𝘁𝘀 d\'où les représentants des OLM se sont réunis pour partager leurs réalisations et célébrer les succès collectifs.\n\nLa JCI Bardo a brillé par son engagement indéfectible envers l\'efficacité et la réalisation de résultats concrets. Grâce à son approche méthodique et à la passion de ses membres , cette performance remarquable témoigne l\'engagement continu de la JCI Bardo à apporter des changements positifs et durables dans sa communauté.✨✨"},
  ]

  constructor() { }

  ngOnInit(): void {
  }

}
